version: "3.8"

services:
  lt-server:
    image: vyacheslavbadaev/localtunnel-fork-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "-r", "esm", "./bin/server", "--port", "3000", "--domain", "lt.server-badaev-dev.work"]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: localtunnel*
    labels:
      - traefik.http.middlewares.lt-timeout.forwardingtimeouts.dialTimeout=30s
      - traefik.http.middlewares.lt-timeout.forwardingtimeouts.responseHeaderTimeout=60s
      - traefik.http.middlewares.lt-timeout.forwardingtimeouts.idleTimeout=3600s
      - traefik.http.routers.https-0-zg0s8gsgog4cgkoksgwcwkwc-lt-server.middlewares=gzip,lt-timeout
