version: "3.8"

services:
  lt-server:
    image: vyacheslavbadaev/localtunnel-fork-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "-r", "esm", "./bin/server", "--port", "3000", "--domain", "lt.server-badaev-dev.work"]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: localtunnel*
    labels:
      - 'traefik.http.routers.http-0-zg0s8gsgog4cgkoksgwcwkwc-lt-server.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.lt.server-badaev-dev.work`) && PathPrefix(`/`)'
