version: "3.8"

services:
  lt-server:
    image: vyacheslavbadaev/localtunnel-fork-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "-r", "esm", "./bin/server", "--port", "3000"]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: localtunnel*
    labels:
      - 'traefik.http.routers.https-wildcard-lt-server.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.lt.server-badaev-dev.work`) && PathPrefix(`/`)'
      - traefik.http.routers.https-wildcard-lt-server.entryPoints=https
      - traefik.http.routers.https-wildcard-lt-server.tls.certresolver=letsencrypt
      - traefik.http.routers.https-wildcard-lt-server.tls=true
      - traefik.http.routers.https-wildcard-lt-server.middlewares=gzip
      - traefik.http.routers.https-wildcard-lt-server.service=lt-server
      - traefik.http.services.lt-server.loadbalancer.server.port=3000
